name: Backend CI

on:
  push:
    paths:
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements.txt'

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend check
        run: echo "✅ Backend check passed. Add tests or linters here."
