name: Frontend Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check HTML/CSS syntax
        run: |
          echo "You can add linting tools here if needed."
          echo "Currently just a placeholder for frontend checks."
