name: Frontend CI

on:
  push:
    paths:
      - '**/*.html'
      - '**/*.css'
  pull_request:
    paths:
      - '**/*.html'
      - '**/*.css'

jobs:
  check-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check HTML/CSS files
        run: echo "✅ Frontend files pushed. You can add HTML/CSS validators here."
