name: Pylint Code Linting

on:
  push:
    branches:
      - main  # or master, or any branch you want to trigger on push
  pull_request:
    branches:
      - main  # or the branch you want for PRs

jobs:
  pylint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can use the Python version your project requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        pylint app.py  || true # You can specify other files or directories here, like '*.py'
